// Code generated by "stringer -type ConditionType"; DO NOT EDIT.

package plans

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidCondition-0]
	_ = x[ResourcePrecondition-1]
	_ = x[ResourcePostcondition-2]
	_ = x[OutputPrecondition-3]
}

const _ConditionType_name = "InvalidConditionResourcePreconditionResourcePostconditionOutputPrecondition"

var _ConditionType_index = [...]uint8{0, 16, 36, 57, 75}

func (i ConditionType) String() string {
	if i < 0 || i >= ConditionType(len(_ConditionType_index)-1) {
		return "ConditionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConditionType_name[_ConditionType_index[i]:_ConditionType_index[i+1]]
}
